import json
import numpy as np

CURVE_V2 = "data/tradeoff_curve_v2.json"
TUNED = "data/tuned_metrics.json"
SCREENER = "data/screener_metrics.json"
OUT = "notes/paper_tables_v2.tex"
OPS_TARGETS = [0.90, 0.94, 0.95, 0.96, 0.97, 0.98]


def curve_point(records, model, cov):
    for r in records:
        if r["model"] == model and abs(r["coverage_target"] - cov) < 1e-9:
            return r
    raise ValueError(f"{model} @ {cov} missing")


def fit_m2(tuned, family):
    rows = [r for r in tuned["records"] if r["family"] == family and r["metric"] == "m2"]
    mae = np.array([r["mae"] for r in rows]) * 1000.0
    r2 = np.array([r["r2"] for r in rows])
    return np.mean(mae), np.std(mae), np.mean(r2), np.std(r2)


def committed_row(screener, model):
    rows = [r for r in screener["records"] if r["model"] == model]
    mae = np.array([r["mae"] for r in rows]) * 1000.0
    r2 = np.array([r["r2"] for r in rows])
    esc = np.array([r["escalation"] for r in rows]) * 100.0
    mis = np.array([r["missed_viol"] for r in rows]) * 100.0
    spd = np.array([r["net_speedup"] for r in rows])
    return dict(mae=(mae.mean(), mae.std()), r2=(r2.mean(), r2.std()),
                esc=(esc.mean(), esc.std()), mis=(mis.mean(), mis.std()),
                spd=(spd.mean(), spd.std()))


def ops_body(records):
    lines = []
    for model in ("ridge", "histgb"):
        label = "ridge " if model == "ridge" else "histgb"
        for cov in OPS_TARGETS:
            r = curve_point(records, model, cov)
            e, es = r["escalation"] * 100, r["escalation_std"] * 100
            c, cs = r["coverage_emp"] * 100, r["coverage_emp_std"] * 100
            m, msd = r["missed_viol"] * 100, r["missed_viol_std"] * 100
            s, ss = r["net_speedup"], r["net_speedup_std"]
            lines.append(f"{label} & {cov:.2f} & {e:.1f}$\\pm${es:.1f} & {c:.1f}$\\pm${cs:.1f} & "
                         f"{m:.2f}$\\pm${msd:.2f} & {s:.2f}$\\pm${ss:.2f} \\\\")
    return "\n".join(lines)


def models_body(records, tuned, screener):
    lines = []
    p = committed_row(screener, "persistence")
    lines.append(f"persistence & {p['mae'][0]:.1f}$\\pm${p['mae'][1]:.1f} & "
                 f"$-0.06\\pm0.00$ & {p['esc'][0]:.1f}$\\pm${p['esc'][1]:.1f} & "
                 f"{p['mis'][0]:.2f}$\\pm${p['mis'][1]:.2f} & {p['spd'][0]:.2f}$\\pm${p['spd'][1]:.2f} \\\\")
    t = committed_row(screener, "train_mean")
    lines.append(f"train mean  & {t['mae'][0]:.1f}$\\pm${t['mae'][1]:.1f} & "
                 f"$-0.00\\pm0.00$ & {t['esc'][0]:.1f}$\\pm${t['esc'][1]:.1f} & "
                 f"{t['mis'][0]:.2f}$\\pm${t['mis'][1]:.2f} & $2.1{{\\times}}10^{{7\\dagger}}$ \\\\")
    for model in ("ridge", "histgb"):
        mae_m, mae_s, r2_m, r2_s = fit_m2(tuned, model)
        r = curve_point(records, model, 0.90)
        e, es = r["escalation"] * 100, r["escalation_std"] * 100
        m, msd = r["missed_viol"] * 100, r["missed_viol_std"] * 100
        s, ss = r["net_speedup"], r["net_speedup_std"]
        name = "ridge      " if model == "ridge" else "histgb     "
        lines.append(f"{name} & {mae_m:.1f}$\\pm${mae_s:.1f} & {r2_m:.2f}$\\pm${r2_s:.2f} & "
                     f"{e:.1f}$\\pm${es:.1f} & {m:.2f}$\\pm${msd:.2f} & {s:.2f}$\\pm${ss:.2f} \\\\")
    return "\n".join(lines)


def main():
    with open(CURVE_V2) as f:
        records = json.load(f)["records"]
    with open(TUNED) as f:
        tuned = json.load(f)
    with open(SCREENER) as f:
        screener = json.load(f)

    ops = ops_body(records)
    models = models_body(records, tuned, screener)

    text = (
        "% v2 promoted-model (M2 gate-aware tuned) table bodies. Generated by\n"
        "% scripts/emit_v2_tables.py from data/tradeoff_curve_v2.json, data/tuned_metrics.json,\n"
        "% and (persistence/train-mean rows only) data/screener_metrics.json.\n"
        "% COLUMN STRUCTURE MUST BE RECONCILED AGAINST paper_current.tex BEFORE PASTING - this\n"
        "% file guarantees the NUMBERS, not the surrounding tabular spec.\n"
        "% persistence and train-mean rows are copied verbatim from the committed models and must\n"
        "% match the committed tab:models rows byte-for-byte.\n\n"
        "%%%%%%%%%% tab:ops body (12 rows) %%%%%%%%%%\n" + ops + "\n\n"
        "%%%%%%%%%% tab:models body (persistence/train-mean copied; ridge/histgb v2) %%%%%%%%%%\n"
        + models + "\n")
    with open(OUT, "w") as f:
        f.write(text)
    print(f"wrote {OUT}")
    print("\n--- tab:ops ---\n" + ops)
    print("\n--- tab:models ---\n" + models)


if __name__ == "__main__":
    main()
